-- Seed Demo Invoice
-- Creates a demo user, profile, and a publicly-visible USDT invoice
-- used by the landing-page "See Demo Invoice" button.

-- ─── 0. Ensure invoices are publicly readable ─────────────────────────────
-- The initial schema already creates this policy, but guard with DO NOTHING
-- in case it was dropped or the schema was partially applied.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'invoices'
          AND policyname = 'Anyone can view invoices by UUID'
    ) THEN
        EXECUTE $policy$
            CREATE POLICY "Anyone can view invoices by UUID"
                ON invoices FOR SELECT
                USING (true)
        $policy$;
    END IF;
END $$;

DO $$
DECLARE
    v_demo_user_id UUID := '00000000-0000-0000-0000-000000000001';
BEGIN

    -- ─── 1. Demo user in auth.users ──────────────────────────────────────────
    INSERT INTO auth.users (
        id,
        instance_id,
        aud,
        role,
        email,
        encrypted_password,
        email_confirmed_at,
        raw_app_meta_data,
        raw_user_meta_data,
        created_at,
        updated_at
    )
    VALUES (
        v_demo_user_id,
        '00000000-0000-0000-0000-000000000000',
        'authenticated',
        'authenticated',
        'demo@linkvoices.com',
        '', -- no real password; demo account is never logged in to
        NOW(),
        '{"provider":"email","providers":["email"]}'::jsonb,
        '{"full_name":"Linkvoices Demo"}'::jsonb,
        NOW(),
        NOW()
    )
    ON CONFLICT (id) DO NOTHING;

    -- ─── 2. Profile ───────────────────────────────────────────────────────────
    -- Use DO UPDATE so the wallet is set even if the handle_new_user trigger
    -- already created the row (trigger fires before this INSERT runs).
    INSERT INTO profiles (
        id,
        email,
        full_name,
        usdt_trc20_wallet
    )
    VALUES (
        v_demo_user_id,
        'demo@linkvoices.com',
        'Linkvoices Demo',
        'TQdwPs3pjhXLzTmL1mV8bNRZhF4Kd5Gnwe'
    )
    ON CONFLICT (id) DO UPDATE
        SET usdt_trc20_wallet = EXCLUDED.usdt_trc20_wallet,
            full_name         = EXCLUDED.full_name;

    -- ─── 3. Demo invoice ──────────────────────────────────────────────────────
    INSERT INTO invoices (
        invoice_uuid,
        user_id,
        number,
        issue_date,
        due_date,
        from_email,
        to_email,
        from_info,
        to_info,
        currency,
        wallet_address,
        total,
        items,
        status,
        notes
    )
    VALUES (
        'fff45e65-9088-4928-9261-38abe1944cec',
        v_demo_user_id,
        'DEMO-001',
        '2026-05-01',
        '2026-05-15',
        'demo@linkvoices.com',
        'client@example.com',
        '{
            "name":    "Linkvoices Demo Studio",
            "address": "123 Blockchain Ave, San Francisco, CA 94107",
            "phone":   "+1 (555) 000-0001"
        }'::jsonb,
        '{
            "name":    "Acme Corp",
            "address": "456 Startup Blvd, New York, NY 10001",
            "phone":   "+1 (555) 000-0002"
        }'::jsonb,
        'usdt',
        'TQdwPs3pjhXLzTmL1mV8bNRZhF4Kd5Gnwe',
        5310.00,
        '[
            {
                "name": "UI/UX Design — landing page & dashboard",
                "quantity": 3,
                "rate": 350.00,
                "amount": 1050.00
            },
            {
                "name": "Frontend Development (Nuxt 3)",
                "quantity": 40,
                "rate": 65.00,
                "amount": 2600.00
            },
            {
                "name": "Backend API Integration",
                "quantity": 20,
                "rate": 65.00,
                "amount": 1300.00
            },
            {
                "name": "Project Management & Review",
                "quantity": 8,
                "rate": 45.00,
                "amount": 360.00
            }
        ]'::jsonb,
        'not_paid',
        'This is a demo invoice generated by Linkvoices. All wallet addresses and contact details are fictional.'
    )
    ON CONFLICT (invoice_uuid) DO UPDATE
        SET items = EXCLUDED.items;

END $$;
